name: Deploy GCP VPC
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Check if Network Exists
        run: |
          # Your script to check if the network exists
          # If it exists, set a flag or variable to indicate that
          # Otherwise, proceed to create the network
          # Example: check_network_existence.sh

      - name: Terraform Apply/Create Network
        if: ${{ success() }}
        run: terraform apply -auto-approve

      - name: Check if Network is Created/Updated
        if: ${{ success() }}
        run: |
          # Your script to verify if the network was successfully created/updated
          # Example: check_network_status.sh

      - name: Terraform Apply/Update Resources
        if: ${{ success() }}
        run: terraform apply -auto-approve
