name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Check if network exists
        id: check_network
        run: |
          network_exist=$(terraform output -json | jq -r '.shared_vpc_self_link.value')
          if [[ $network_exist == "null" ]]; then
            echo "::set-output name=network_exists::false"
          else
            echo "::set-output name=network_exists::true"
          fi

      - name: Terraform Plan
        if: steps.check_network.outputs.network_exists == 'false'
        run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply/Create
        if: steps.check_network.outputs.network_exists == 'false'
        run: terraform apply -input=false tfplan

      - name: Terraform Apply/Update
        if: steps.check_network.outputs.network_exists == 'true'
        run: terraform apply -input=false

      - name: Terraform Show Output
        run: terraform output
